name: greengrass
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10

  
  # State management
  get: ^4.6.6
  
  # UI packages
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  path: ^1.8.3
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  get_storage: ^2.1.1

  google_fonts: ^6.1.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Add your assets here if needed
  assets:
    - assets/images/
  #   - assets/icons/
  
  # Add fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic